language: java
jdk:
 - oraclejdk8

install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install


script:
  mvn org.apache.maven.plugins:maven-assembly-plugin:2.6:assembly -DdescriptorId=jar-with-dependencies package

addons:
  sonarcloud:
    organization: "sweihmws2018-19"

deploy:
  provider: lambda
  function_name: "Soup-IT"
  region: "us-east-1"
  role: "arn:aws:iam::567943339894:role/lambda_basic_execution"
  runtime: "java8"
  handler_name: "main.java.soupit.ColorPickerStreamHandler"